version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: infra/docker/dev/web.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web/src:/app/src
      - ./apps/web/public:/app/public
      - ./apps/web/next.config.js:/app/next.config.js
      - ./apps/web/tsconfig.json:/app/tsconfig.json
      - ./apps/web/postcss.config.js:/app/postcss.config.js
      - ./apps/web/tailwind.config.ts:/app/tailwind.config.ts
      - ./packages/shared:/packages/shared
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - WATCHPACK_POLLING=true
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: infra/docker/dev/api.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./apps/api:/app
      - ./packages/ai:/packages/ai
      - ./packages/shared:/packages/shared
    environment:
      - ENVIRONMENT=development
      - OLLAMA_HOST=http://ollama:11434
      - QDRANT_HOST=http://qdrant:6333
      - OLLAMA_MODEL=mistral
      - QDRANT_COLLECTION=portfolio_knowledge
    depends_on:
      - ollama
      - qdrant
      - ai
    restart: unless-stopped

  ai:
    build:
      context: .
      dockerfile: infra/docker/dev/ai.Dockerfile
    volumes:
      - ./packages/ai:/packages/ai
    environment:
      - NODE_ENV=development
      - OLLAMA_HOST=http://ollama:11434
      - QDRANT_HOST=http://qdrant:6333
      - OLLAMA_MODEL=mistral
      - QDRANT_COLLECTION=portfolio_knowledge
    depends_on:
      - ollama
      - qdrant
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    command: >
      sh -c "ollama pull mistral && ollama serve"

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT_ALLOW_CREATION=true
    restart: unless-stopped

volumes:
  ollama_data:
  qdrant_data: 